services:
  uai_food_postgres:
    container_name: uai-food-db
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=uai-food-db
    networks:
      - network_uai_food
    volumes:
      - postgres_data:/bitnami/postgresql

  uai_food_redis:
    container_name: uai-food-redis
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - network_uai_food
    volumes:
      - redis_data:/data

#  uai_food_app:
#    container_name: uai-food-app
#    build:
#      context: .
#    ports:
#      - "3333:3333"
#    networks:
#      - network_uai_food
#    depends_on:
#      - uai_food_postgres
#    environment:
#      - PORT:3333
#      - DATABASE_URL:postgresql://docker:docker@uai_food_postgres:5432/uai-food-db?schema=public
#      - BASE_URL:http://localhost:3333
#    volumes:
#      - .:/usr/src

networks:
  network_uai_food:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
